version: '3'

tasks:
  default:
    silent: true
    cmds:
      - echo $'To list all tasks run:\n\n\t task --list-all\n'
      - task --list --sort=none

  check:
    desc: Run all checks (used in CI)
    cmds:
      - task: lint
      - task: test
      - task: build

  clean:
    cmds:
      - rm -f glean
      - go clean
      - rm -rf dist/

  build:
    cmds:
      - go build -o glean

  test:
    cmds:
      - go test ./... -v

  lint:
    cmds:
      - golangci-lint run

  lint:fix:
    cmds:
      - golangci-lint run --fix


  install:
    desc: Install the CLI locally
    cmds:
      - go install
