/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PreviewStructuredTextResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreviewStructuredTextResponse{}

// PreviewStructuredTextResponse struct for PreviewStructuredTextResponse
type PreviewStructuredTextResponse struct {
	StructuredText StructuredText `json:"structuredText"`
	// A list of links the user doesn't have access to.
	DocsInaccessibleToUser []string `json:"docsInaccessibleToUser,omitempty"`
	CombinedAnswerText StructuredText `json:"combinedAnswerText"`
}

type _PreviewStructuredTextResponse PreviewStructuredTextResponse

// NewPreviewStructuredTextResponse instantiates a new PreviewStructuredTextResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreviewStructuredTextResponse(structuredText StructuredText, combinedAnswerText StructuredText) *PreviewStructuredTextResponse {
	this := PreviewStructuredTextResponse{}
	this.StructuredText = structuredText
	this.CombinedAnswerText = combinedAnswerText
	return &this
}

// NewPreviewStructuredTextResponseWithDefaults instantiates a new PreviewStructuredTextResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreviewStructuredTextResponseWithDefaults() *PreviewStructuredTextResponse {
	this := PreviewStructuredTextResponse{}
	return &this
}

// GetStructuredText returns the StructuredText field value
func (o *PreviewStructuredTextResponse) GetStructuredText() StructuredText {
	if o == nil {
		var ret StructuredText
		return ret
	}

	return o.StructuredText
}

// GetStructuredTextOk returns a tuple with the StructuredText field value
// and a boolean to check if the value has been set.
func (o *PreviewStructuredTextResponse) GetStructuredTextOk() (*StructuredText, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StructuredText, true
}

// SetStructuredText sets field value
func (o *PreviewStructuredTextResponse) SetStructuredText(v StructuredText) {
	o.StructuredText = v
}

// GetDocsInaccessibleToUser returns the DocsInaccessibleToUser field value if set, zero value otherwise.
func (o *PreviewStructuredTextResponse) GetDocsInaccessibleToUser() []string {
	if o == nil || IsNil(o.DocsInaccessibleToUser) {
		var ret []string
		return ret
	}
	return o.DocsInaccessibleToUser
}

// GetDocsInaccessibleToUserOk returns a tuple with the DocsInaccessibleToUser field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreviewStructuredTextResponse) GetDocsInaccessibleToUserOk() ([]string, bool) {
	if o == nil || IsNil(o.DocsInaccessibleToUser) {
		return nil, false
	}
	return o.DocsInaccessibleToUser, true
}

// HasDocsInaccessibleToUser returns a boolean if a field has been set.
func (o *PreviewStructuredTextResponse) HasDocsInaccessibleToUser() bool {
	if o != nil && !IsNil(o.DocsInaccessibleToUser) {
		return true
	}

	return false
}

// SetDocsInaccessibleToUser gets a reference to the given []string and assigns it to the DocsInaccessibleToUser field.
func (o *PreviewStructuredTextResponse) SetDocsInaccessibleToUser(v []string) {
	o.DocsInaccessibleToUser = v
}

// GetCombinedAnswerText returns the CombinedAnswerText field value
func (o *PreviewStructuredTextResponse) GetCombinedAnswerText() StructuredText {
	if o == nil {
		var ret StructuredText
		return ret
	}

	return o.CombinedAnswerText
}

// GetCombinedAnswerTextOk returns a tuple with the CombinedAnswerText field value
// and a boolean to check if the value has been set.
func (o *PreviewStructuredTextResponse) GetCombinedAnswerTextOk() (*StructuredText, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CombinedAnswerText, true
}

// SetCombinedAnswerText sets field value
func (o *PreviewStructuredTextResponse) SetCombinedAnswerText(v StructuredText) {
	o.CombinedAnswerText = v
}

func (o PreviewStructuredTextResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreviewStructuredTextResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["structuredText"] = o.StructuredText
	if !IsNil(o.DocsInaccessibleToUser) {
		toSerialize["docsInaccessibleToUser"] = o.DocsInaccessibleToUser
	}
	toSerialize["combinedAnswerText"] = o.CombinedAnswerText
	return toSerialize, nil
}

func (o *PreviewStructuredTextResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"structuredText",
		"combinedAnswerText",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPreviewStructuredTextResponse := _PreviewStructuredTextResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPreviewStructuredTextResponse)

	if err != nil {
		return err
	}

	*o = PreviewStructuredTextResponse(varPreviewStructuredTextResponse)

	return err
}

type NullablePreviewStructuredTextResponse struct {
	value *PreviewStructuredTextResponse
	isSet bool
}

func (v NullablePreviewStructuredTextResponse) Get() *PreviewStructuredTextResponse {
	return v.value
}

func (v *NullablePreviewStructuredTextResponse) Set(val *PreviewStructuredTextResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePreviewStructuredTextResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePreviewStructuredTextResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreviewStructuredTextResponse(val *PreviewStructuredTextResponse) *NullablePreviewStructuredTextResponse {
	return &NullablePreviewStructuredTextResponse{value: val, isSet: true}
}

func (v NullablePreviewStructuredTextResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreviewStructuredTextResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


