/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
)

// checks if the SummarizeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SummarizeResponse{}

// SummarizeResponse struct for SummarizeResponse
type SummarizeResponse struct {
	Error *SummarizeResponseError `json:"error,omitempty"`
	Summary *Summary `json:"summary,omitempty"`
	// An opaque token that represents this summary in this particular query. To be used for /feedback reporting.
	TrackingToken *string `json:"trackingToken,omitempty"`
}

// NewSummarizeResponse instantiates a new SummarizeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSummarizeResponse() *SummarizeResponse {
	this := SummarizeResponse{}
	return &this
}

// NewSummarizeResponseWithDefaults instantiates a new SummarizeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSummarizeResponseWithDefaults() *SummarizeResponse {
	this := SummarizeResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *SummarizeResponse) GetError() SummarizeResponseError {
	if o == nil || IsNil(o.Error) {
		var ret SummarizeResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummarizeResponse) GetErrorOk() (*SummarizeResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *SummarizeResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given SummarizeResponseError and assigns it to the Error field.
func (o *SummarizeResponse) SetError(v SummarizeResponseError) {
	o.Error = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *SummarizeResponse) GetSummary() Summary {
	if o == nil || IsNil(o.Summary) {
		var ret Summary
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummarizeResponse) GetSummaryOk() (*Summary, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *SummarizeResponse) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given Summary and assigns it to the Summary field.
func (o *SummarizeResponse) SetSummary(v Summary) {
	o.Summary = &v
}

// GetTrackingToken returns the TrackingToken field value if set, zero value otherwise.
func (o *SummarizeResponse) GetTrackingToken() string {
	if o == nil || IsNil(o.TrackingToken) {
		var ret string
		return ret
	}
	return *o.TrackingToken
}

// GetTrackingTokenOk returns a tuple with the TrackingToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SummarizeResponse) GetTrackingTokenOk() (*string, bool) {
	if o == nil || IsNil(o.TrackingToken) {
		return nil, false
	}
	return o.TrackingToken, true
}

// HasTrackingToken returns a boolean if a field has been set.
func (o *SummarizeResponse) HasTrackingToken() bool {
	if o != nil && !IsNil(o.TrackingToken) {
		return true
	}

	return false
}

// SetTrackingToken gets a reference to the given string and assigns it to the TrackingToken field.
func (o *SummarizeResponse) SetTrackingToken(v string) {
	o.TrackingToken = &v
}

func (o SummarizeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SummarizeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.TrackingToken) {
		toSerialize["trackingToken"] = o.TrackingToken
	}
	return toSerialize, nil
}

type NullableSummarizeResponse struct {
	value *SummarizeResponse
	isSet bool
}

func (v NullableSummarizeResponse) Get() *SummarizeResponse {
	return v.value
}

func (v *NullableSummarizeResponse) Set(val *SummarizeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSummarizeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSummarizeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSummarizeResponse(val *SummarizeResponse) *NullableSummarizeResponse {
	return &NullableSummarizeResponse{value: val, isSet: true}
}

func (v NullableSummarizeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSummarizeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


