/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the LabeledCountInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LabeledCountInfo{}

// LabeledCountInfo struct for LabeledCountInfo
type LabeledCountInfo struct {
	// Label for the included count information.
	Label string `json:"label"`
	// List of data points for counts for a given date period.
	CountInfo []CountInfo `json:"countInfo,omitempty"`
}

type _LabeledCountInfo LabeledCountInfo

// NewLabeledCountInfo instantiates a new LabeledCountInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLabeledCountInfo(label string) *LabeledCountInfo {
	this := LabeledCountInfo{}
	this.Label = label
	return &this
}

// NewLabeledCountInfoWithDefaults instantiates a new LabeledCountInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLabeledCountInfoWithDefaults() *LabeledCountInfo {
	this := LabeledCountInfo{}
	return &this
}

// GetLabel returns the Label field value
func (o *LabeledCountInfo) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *LabeledCountInfo) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *LabeledCountInfo) SetLabel(v string) {
	o.Label = v
}

// GetCountInfo returns the CountInfo field value if set, zero value otherwise.
func (o *LabeledCountInfo) GetCountInfo() []CountInfo {
	if o == nil || IsNil(o.CountInfo) {
		var ret []CountInfo
		return ret
	}
	return o.CountInfo
}

// GetCountInfoOk returns a tuple with the CountInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LabeledCountInfo) GetCountInfoOk() ([]CountInfo, bool) {
	if o == nil || IsNil(o.CountInfo) {
		return nil, false
	}
	return o.CountInfo, true
}

// HasCountInfo returns a boolean if a field has been set.
func (o *LabeledCountInfo) HasCountInfo() bool {
	if o != nil && !IsNil(o.CountInfo) {
		return true
	}

	return false
}

// SetCountInfo gets a reference to the given []CountInfo and assigns it to the CountInfo field.
func (o *LabeledCountInfo) SetCountInfo(v []CountInfo) {
	o.CountInfo = v
}

func (o LabeledCountInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LabeledCountInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["label"] = o.Label
	if !IsNil(o.CountInfo) {
		toSerialize["countInfo"] = o.CountInfo
	}
	return toSerialize, nil
}

func (o *LabeledCountInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"label",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLabeledCountInfo := _LabeledCountInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLabeledCountInfo)

	if err != nil {
		return err
	}

	*o = LabeledCountInfo(varLabeledCountInfo)

	return err
}

type NullableLabeledCountInfo struct {
	value *LabeledCountInfo
	isSet bool
}

func (v NullableLabeledCountInfo) Get() *LabeledCountInfo {
	return v.value
}

func (v *NullableLabeledCountInfo) Set(val *LabeledCountInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableLabeledCountInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableLabeledCountInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLabeledCountInfo(val *LabeledCountInfo) *NullableLabeledCountInfo {
	return &NullableLabeledCountInfo{value: val, isSet: true}
}

func (v NullableLabeledCountInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLabeledCountInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


