/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
)

// checks if the DocumentContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentContent{}

// DocumentContent struct for DocumentContent
type DocumentContent struct {
	// The plaintext content of the document.
	FullTextList []string `json:"fullTextList,omitempty"`
}

// NewDocumentContent instantiates a new DocumentContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentContent() *DocumentContent {
	this := DocumentContent{}
	return &this
}

// NewDocumentContentWithDefaults instantiates a new DocumentContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentContentWithDefaults() *DocumentContent {
	this := DocumentContent{}
	return &this
}

// GetFullTextList returns the FullTextList field value if set, zero value otherwise.
func (o *DocumentContent) GetFullTextList() []string {
	if o == nil || IsNil(o.FullTextList) {
		var ret []string
		return ret
	}
	return o.FullTextList
}

// GetFullTextListOk returns a tuple with the FullTextList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DocumentContent) GetFullTextListOk() ([]string, bool) {
	if o == nil || IsNil(o.FullTextList) {
		return nil, false
	}
	return o.FullTextList, true
}

// HasFullTextList returns a boolean if a field has been set.
func (o *DocumentContent) HasFullTextList() bool {
	if o != nil && !IsNil(o.FullTextList) {
		return true
	}

	return false
}

// SetFullTextList gets a reference to the given []string and assigns it to the FullTextList field.
func (o *DocumentContent) SetFullTextList(v []string) {
	o.FullTextList = v
}

func (o DocumentContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FullTextList) {
		toSerialize["fullTextList"] = o.FullTextList
	}
	return toSerialize, nil
}

type NullableDocumentContent struct {
	value *DocumentContent
	isSet bool
}

func (v NullableDocumentContent) Get() *DocumentContent {
	return v.value
}

func (v *NullableDocumentContent) Set(val *DocumentContent) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentContent) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentContent(val *DocumentContent) *NullableDocumentContent {
	return &NullableDocumentContent{value: val, isSet: true}
}

func (v NullableDocumentContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


