/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
)

// checks if the EditDocumentCollectionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditDocumentCollectionsResponse{}

// EditDocumentCollectionsResponse struct for EditDocumentCollectionsResponse
type EditDocumentCollectionsResponse struct {
	Document *Document `json:"document,omitempty"`
}

// NewEditDocumentCollectionsResponse instantiates a new EditDocumentCollectionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditDocumentCollectionsResponse() *EditDocumentCollectionsResponse {
	this := EditDocumentCollectionsResponse{}
	return &this
}

// NewEditDocumentCollectionsResponseWithDefaults instantiates a new EditDocumentCollectionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditDocumentCollectionsResponseWithDefaults() *EditDocumentCollectionsResponse {
	this := EditDocumentCollectionsResponse{}
	return &this
}

// GetDocument returns the Document field value if set, zero value otherwise.
func (o *EditDocumentCollectionsResponse) GetDocument() Document {
	if o == nil || IsNil(o.Document) {
		var ret Document
		return ret
	}
	return *o.Document
}

// GetDocumentOk returns a tuple with the Document field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditDocumentCollectionsResponse) GetDocumentOk() (*Document, bool) {
	if o == nil || IsNil(o.Document) {
		return nil, false
	}
	return o.Document, true
}

// HasDocument returns a boolean if a field has been set.
func (o *EditDocumentCollectionsResponse) HasDocument() bool {
	if o != nil && !IsNil(o.Document) {
		return true
	}

	return false
}

// SetDocument gets a reference to the given Document and assigns it to the Document field.
func (o *EditDocumentCollectionsResponse) SetDocument(v Document) {
	o.Document = &v
}

func (o EditDocumentCollectionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditDocumentCollectionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Document) {
		toSerialize["document"] = o.Document
	}
	return toSerialize, nil
}

type NullableEditDocumentCollectionsResponse struct {
	value *EditDocumentCollectionsResponse
	isSet bool
}

func (v NullableEditDocumentCollectionsResponse) Get() *EditDocumentCollectionsResponse {
	return v.value
}

func (v *NullableEditDocumentCollectionsResponse) Set(val *EditDocumentCollectionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEditDocumentCollectionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEditDocumentCollectionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditDocumentCollectionsResponse(val *EditDocumentCollectionsResponse) *NullableEditDocumentCollectionsResponse {
	return &NullableEditDocumentCollectionsResponse{value: val, isSet: true}
}

func (v NullableEditDocumentCollectionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditDocumentCollectionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


