/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListAnswersResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAnswersResponse{}

// ListAnswersResponse struct for ListAnswersResponse
type ListAnswersResponse struct {
	// List of answers with tracking tokens.
	AnswerResults []AnswerResult `json:"answerResults"`
}

type _ListAnswersResponse ListAnswersResponse

// NewListAnswersResponse instantiates a new ListAnswersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAnswersResponse(answerResults []AnswerResult) *ListAnswersResponse {
	this := ListAnswersResponse{}
	this.AnswerResults = answerResults
	return &this
}

// NewListAnswersResponseWithDefaults instantiates a new ListAnswersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAnswersResponseWithDefaults() *ListAnswersResponse {
	this := ListAnswersResponse{}
	return &this
}

// GetAnswerResults returns the AnswerResults field value
func (o *ListAnswersResponse) GetAnswerResults() []AnswerResult {
	if o == nil {
		var ret []AnswerResult
		return ret
	}

	return o.AnswerResults
}

// GetAnswerResultsOk returns a tuple with the AnswerResults field value
// and a boolean to check if the value has been set.
func (o *ListAnswersResponse) GetAnswerResultsOk() ([]AnswerResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.AnswerResults, true
}

// SetAnswerResults sets field value
func (o *ListAnswersResponse) SetAnswerResults(v []AnswerResult) {
	o.AnswerResults = v
}

func (o ListAnswersResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAnswersResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["answerResults"] = o.AnswerResults
	return toSerialize, nil
}

func (o *ListAnswersResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"answerResults",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAnswersResponse := _ListAnswersResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListAnswersResponse)

	if err != nil {
		return err
	}

	*o = ListAnswersResponse(varListAnswersResponse)

	return err
}

type NullableListAnswersResponse struct {
	value *ListAnswersResponse
	isSet bool
}

func (v NullableListAnswersResponse) Get() *ListAnswersResponse {
	return v.value
}

func (v *NullableListAnswersResponse) Set(val *ListAnswersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListAnswersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListAnswersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAnswersResponse(val *ListAnswersResponse) *NullableListAnswersResponse {
	return &NullableListAnswersResponse{value: val, isSet: true}
}

func (v NullableListAnswersResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAnswersResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


