/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
	"time"
)

// checks if the ViewerInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ViewerInfo{}

// ViewerInfo struct for ViewerInfo
type ViewerInfo struct {
	// DEPRECATED - use permissions instead. Viewer's role on the specific document.
	// Deprecated
	Role *string `json:"role,omitempty"`
	LastViewedTime *time.Time `json:"lastViewedTime,omitempty"`
}

// NewViewerInfo instantiates a new ViewerInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewViewerInfo() *ViewerInfo {
	this := ViewerInfo{}
	return &this
}

// NewViewerInfoWithDefaults instantiates a new ViewerInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewViewerInfoWithDefaults() *ViewerInfo {
	this := ViewerInfo{}
	return &this
}

// GetRole returns the Role field value if set, zero value otherwise.
// Deprecated
func (o *ViewerInfo) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *ViewerInfo) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *ViewerInfo) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
// Deprecated
func (o *ViewerInfo) SetRole(v string) {
	o.Role = &v
}

// GetLastViewedTime returns the LastViewedTime field value if set, zero value otherwise.
func (o *ViewerInfo) GetLastViewedTime() time.Time {
	if o == nil || IsNil(o.LastViewedTime) {
		var ret time.Time
		return ret
	}
	return *o.LastViewedTime
}

// GetLastViewedTimeOk returns a tuple with the LastViewedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ViewerInfo) GetLastViewedTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastViewedTime) {
		return nil, false
	}
	return o.LastViewedTime, true
}

// HasLastViewedTime returns a boolean if a field has been set.
func (o *ViewerInfo) HasLastViewedTime() bool {
	if o != nil && !IsNil(o.LastViewedTime) {
		return true
	}

	return false
}

// SetLastViewedTime gets a reference to the given time.Time and assigns it to the LastViewedTime field.
func (o *ViewerInfo) SetLastViewedTime(v time.Time) {
	o.LastViewedTime = &v
}

func (o ViewerInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ViewerInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	if !IsNil(o.LastViewedTime) {
		toSerialize["lastViewedTime"] = o.LastViewedTime
	}
	return toSerialize, nil
}

type NullableViewerInfo struct {
	value *ViewerInfo
	isSet bool
}

func (v NullableViewerInfo) Get() *ViewerInfo {
	return v.value
}

func (v *NullableViewerInfo) Set(val *ViewerInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableViewerInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableViewerInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableViewerInfo(val *ViewerInfo) *NullableViewerInfo {
	return &NullableViewerInfo{value: val, isSet: true}
}

func (v NullableViewerInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableViewerInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


