/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
	"fmt"
)

// EventStrategyName The name of method used to surface relevant data for a given calendar event.
type EventStrategyName string

// List of EventStrategyName
const (
	CUSTOMER_CARD EventStrategyName = "customerCard"
	NEWS EventStrategyName = "news"
	CALL EventStrategyName = "call"
	EMAIL EventStrategyName = "email"
	MEETING_NOTES EventStrategyName = "meetingNotes"
	LINKED_IN EventStrategyName = "linkedIn"
	RELEVANT_DOCUMENTS EventStrategyName = "relevantDocuments"
	CHAT_FOLLOW_UPS EventStrategyName = "chatFollowUps"
	CONVERSATIONS EventStrategyName = "conversations"
)

// All allowed values of EventStrategyName enum
var AllowedEventStrategyNameEnumValues = []EventStrategyName{
	"customerCard",
	"news",
	"call",
	"email",
	"meetingNotes",
	"linkedIn",
	"relevantDocuments",
	"chatFollowUps",
	"conversations",
}

func (v *EventStrategyName) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EventStrategyName(value)
	for _, existing := range AllowedEventStrategyNameEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EventStrategyName", value)
}

// NewEventStrategyNameFromValue returns a pointer to a valid EventStrategyName
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEventStrategyNameFromValue(v string) (*EventStrategyName, error) {
	ev := EventStrategyName(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EventStrategyName: valid values are %v", v, AllowedEventStrategyNameEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EventStrategyName) IsValid() bool {
	for _, existing := range AllowedEventStrategyNameEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EventStrategyName value
func (v EventStrategyName) Ptr() *EventStrategyName {
	return &v
}

type NullableEventStrategyName struct {
	value *EventStrategyName
	isSet bool
}

func (v NullableEventStrategyName) Get() *EventStrategyName {
	return v.value
}

func (v *NullableEventStrategyName) Set(val *EventStrategyName) {
	v.value = val
	v.isSet = true
}

func (v NullableEventStrategyName) IsSet() bool {
	return v.isSet
}

func (v *NullableEventStrategyName) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventStrategyName(val *EventStrategyName) *NullableEventStrategyName {
	return &NullableEventStrategyName{value: val, isSet: true}
}

func (v NullableEventStrategyName) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventStrategyName) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

