/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadImageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadImageResponse{}

// UploadImageResponse struct for UploadImageResponse
type UploadImageResponse struct {
	// URL of the uploaded image.
	Url string `json:"url"`
	Metadata *ImageMetadata `json:"metadata,omitempty"`
}

type _UploadImageResponse UploadImageResponse

// NewUploadImageResponse instantiates a new UploadImageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadImageResponse(url string) *UploadImageResponse {
	this := UploadImageResponse{}
	this.Url = url
	return &this
}

// NewUploadImageResponseWithDefaults instantiates a new UploadImageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadImageResponseWithDefaults() *UploadImageResponse {
	this := UploadImageResponse{}
	return &this
}

// GetUrl returns the Url field value
func (o *UploadImageResponse) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *UploadImageResponse) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *UploadImageResponse) SetUrl(v string) {
	o.Url = v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *UploadImageResponse) GetMetadata() ImageMetadata {
	if o == nil || IsNil(o.Metadata) {
		var ret ImageMetadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadImageResponse) GetMetadataOk() (*ImageMetadata, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *UploadImageResponse) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given ImageMetadata and assigns it to the Metadata field.
func (o *UploadImageResponse) SetMetadata(v ImageMetadata) {
	o.Metadata = &v
}

func (o UploadImageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadImageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *UploadImageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadImageResponse := _UploadImageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadImageResponse)

	if err != nil {
		return err
	}

	*o = UploadImageResponse(varUploadImageResponse)

	return err
}

type NullableUploadImageResponse struct {
	value *UploadImageResponse
	isSet bool
}

func (v NullableUploadImageResponse) Get() *UploadImageResponse {
	return v.value
}

func (v *NullableUploadImageResponse) Set(val *UploadImageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadImageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadImageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadImageResponse(val *UploadImageResponse) *NullableUploadImageResponse {
	return &NullableUploadImageResponse{value: val, isSet: true}
}

func (v NullableUploadImageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadImageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


