/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
)

// checks if the GeneratedAttachmentContent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeneratedAttachmentContent{}

// GeneratedAttachmentContent Content that has been generated or extrapolated from the documents present in the document field.
type GeneratedAttachmentContent struct {
	// The header describing the generated content.
	DisplayHeader *string `json:"displayHeader,omitempty"`
	// The content that has been generated.
	Text *string `json:"text,omitempty"`
}

// NewGeneratedAttachmentContent instantiates a new GeneratedAttachmentContent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeneratedAttachmentContent() *GeneratedAttachmentContent {
	this := GeneratedAttachmentContent{}
	return &this
}

// NewGeneratedAttachmentContentWithDefaults instantiates a new GeneratedAttachmentContent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeneratedAttachmentContentWithDefaults() *GeneratedAttachmentContent {
	this := GeneratedAttachmentContent{}
	return &this
}

// GetDisplayHeader returns the DisplayHeader field value if set, zero value otherwise.
func (o *GeneratedAttachmentContent) GetDisplayHeader() string {
	if o == nil || IsNil(o.DisplayHeader) {
		var ret string
		return ret
	}
	return *o.DisplayHeader
}

// GetDisplayHeaderOk returns a tuple with the DisplayHeader field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedAttachmentContent) GetDisplayHeaderOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayHeader) {
		return nil, false
	}
	return o.DisplayHeader, true
}

// HasDisplayHeader returns a boolean if a field has been set.
func (o *GeneratedAttachmentContent) HasDisplayHeader() bool {
	if o != nil && !IsNil(o.DisplayHeader) {
		return true
	}

	return false
}

// SetDisplayHeader gets a reference to the given string and assigns it to the DisplayHeader field.
func (o *GeneratedAttachmentContent) SetDisplayHeader(v string) {
	o.DisplayHeader = &v
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *GeneratedAttachmentContent) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedAttachmentContent) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *GeneratedAttachmentContent) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *GeneratedAttachmentContent) SetText(v string) {
	o.Text = &v
}

func (o GeneratedAttachmentContent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeneratedAttachmentContent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayHeader) {
		toSerialize["displayHeader"] = o.DisplayHeader
	}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	return toSerialize, nil
}

type NullableGeneratedAttachmentContent struct {
	value *GeneratedAttachmentContent
	isSet bool
}

func (v NullableGeneratedAttachmentContent) Get() *GeneratedAttachmentContent {
	return v.value
}

func (v *NullableGeneratedAttachmentContent) Set(val *GeneratedAttachmentContent) {
	v.value = val
	v.isSet = true
}

func (v NullableGeneratedAttachmentContent) IsSet() bool {
	return v.isSet
}

func (v *NullableGeneratedAttachmentContent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeneratedAttachmentContent(val *GeneratedAttachmentContent) *NullableGeneratedAttachmentContent {
	return &NullableGeneratedAttachmentContent{value: val, isSet: true}
}

func (v NullableGeneratedAttachmentContent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeneratedAttachmentContent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


