/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
)

// checks if the GetAnswerError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAnswerError{}

// GetAnswerError struct for GetAnswerError
type GetAnswerError struct {
	ErrorType *string `json:"errorType,omitempty"`
	AnswerAuthor *Person `json:"answerAuthor,omitempty"`
}

// NewGetAnswerError instantiates a new GetAnswerError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnswerError() *GetAnswerError {
	this := GetAnswerError{}
	return &this
}

// NewGetAnswerErrorWithDefaults instantiates a new GetAnswerError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnswerErrorWithDefaults() *GetAnswerError {
	this := GetAnswerError{}
	return &this
}

// GetErrorType returns the ErrorType field value if set, zero value otherwise.
func (o *GetAnswerError) GetErrorType() string {
	if o == nil || IsNil(o.ErrorType) {
		var ret string
		return ret
	}
	return *o.ErrorType
}

// GetErrorTypeOk returns a tuple with the ErrorType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAnswerError) GetErrorTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorType) {
		return nil, false
	}
	return o.ErrorType, true
}

// HasErrorType returns a boolean if a field has been set.
func (o *GetAnswerError) HasErrorType() bool {
	if o != nil && !IsNil(o.ErrorType) {
		return true
	}

	return false
}

// SetErrorType gets a reference to the given string and assigns it to the ErrorType field.
func (o *GetAnswerError) SetErrorType(v string) {
	o.ErrorType = &v
}

// GetAnswerAuthor returns the AnswerAuthor field value if set, zero value otherwise.
func (o *GetAnswerError) GetAnswerAuthor() Person {
	if o == nil || IsNil(o.AnswerAuthor) {
		var ret Person
		return ret
	}
	return *o.AnswerAuthor
}

// GetAnswerAuthorOk returns a tuple with the AnswerAuthor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAnswerError) GetAnswerAuthorOk() (*Person, bool) {
	if o == nil || IsNil(o.AnswerAuthor) {
		return nil, false
	}
	return o.AnswerAuthor, true
}

// HasAnswerAuthor returns a boolean if a field has been set.
func (o *GetAnswerError) HasAnswerAuthor() bool {
	if o != nil && !IsNil(o.AnswerAuthor) {
		return true
	}

	return false
}

// SetAnswerAuthor gets a reference to the given Person and assigns it to the AnswerAuthor field.
func (o *GetAnswerError) SetAnswerAuthor(v Person) {
	o.AnswerAuthor = &v
}

func (o GetAnswerError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAnswerError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorType) {
		toSerialize["errorType"] = o.ErrorType
	}
	if !IsNil(o.AnswerAuthor) {
		toSerialize["answerAuthor"] = o.AnswerAuthor
	}
	return toSerialize, nil
}

type NullableGetAnswerError struct {
	value *GetAnswerError
	isSet bool
}

func (v NullableGetAnswerError) Get() *GetAnswerError {
	return v.value
}

func (v *NullableGetAnswerError) Set(val *GetAnswerError) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnswerError) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnswerError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnswerError(val *GetAnswerError) *NullableGetAnswerError {
	return &NullableGetAnswerError{value: val, isSet: true}
}

func (v NullableGetAnswerError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnswerError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


