/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
)

// checks if the GeneratedAttachment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GeneratedAttachment{}

// GeneratedAttachment These are attachments that aren't natively present on the event, and have been smartly suggested.
type GeneratedAttachment struct {
	StrategyName *EventStrategyName `json:"strategyName,omitempty"`
	Documents []Document `json:"documents,omitempty"`
	Person *Person `json:"person,omitempty"`
	Customer *Customer `json:"customer,omitempty"`
	// A list of links to external sources outside of Glean.
	ExternalLinks []StructuredLink `json:"externalLinks,omitempty"`
	Content []GeneratedAttachmentContent `json:"content,omitempty"`
}

// NewGeneratedAttachment instantiates a new GeneratedAttachment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGeneratedAttachment() *GeneratedAttachment {
	this := GeneratedAttachment{}
	return &this
}

// NewGeneratedAttachmentWithDefaults instantiates a new GeneratedAttachment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGeneratedAttachmentWithDefaults() *GeneratedAttachment {
	this := GeneratedAttachment{}
	return &this
}

// GetStrategyName returns the StrategyName field value if set, zero value otherwise.
func (o *GeneratedAttachment) GetStrategyName() EventStrategyName {
	if o == nil || IsNil(o.StrategyName) {
		var ret EventStrategyName
		return ret
	}
	return *o.StrategyName
}

// GetStrategyNameOk returns a tuple with the StrategyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedAttachment) GetStrategyNameOk() (*EventStrategyName, bool) {
	if o == nil || IsNil(o.StrategyName) {
		return nil, false
	}
	return o.StrategyName, true
}

// HasStrategyName returns a boolean if a field has been set.
func (o *GeneratedAttachment) HasStrategyName() bool {
	if o != nil && !IsNil(o.StrategyName) {
		return true
	}

	return false
}

// SetStrategyName gets a reference to the given EventStrategyName and assigns it to the StrategyName field.
func (o *GeneratedAttachment) SetStrategyName(v EventStrategyName) {
	o.StrategyName = &v
}

// GetDocuments returns the Documents field value if set, zero value otherwise.
func (o *GeneratedAttachment) GetDocuments() []Document {
	if o == nil || IsNil(o.Documents) {
		var ret []Document
		return ret
	}
	return o.Documents
}

// GetDocumentsOk returns a tuple with the Documents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedAttachment) GetDocumentsOk() ([]Document, bool) {
	if o == nil || IsNil(o.Documents) {
		return nil, false
	}
	return o.Documents, true
}

// HasDocuments returns a boolean if a field has been set.
func (o *GeneratedAttachment) HasDocuments() bool {
	if o != nil && !IsNil(o.Documents) {
		return true
	}

	return false
}

// SetDocuments gets a reference to the given []Document and assigns it to the Documents field.
func (o *GeneratedAttachment) SetDocuments(v []Document) {
	o.Documents = v
}

// GetPerson returns the Person field value if set, zero value otherwise.
func (o *GeneratedAttachment) GetPerson() Person {
	if o == nil || IsNil(o.Person) {
		var ret Person
		return ret
	}
	return *o.Person
}

// GetPersonOk returns a tuple with the Person field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedAttachment) GetPersonOk() (*Person, bool) {
	if o == nil || IsNil(o.Person) {
		return nil, false
	}
	return o.Person, true
}

// HasPerson returns a boolean if a field has been set.
func (o *GeneratedAttachment) HasPerson() bool {
	if o != nil && !IsNil(o.Person) {
		return true
	}

	return false
}

// SetPerson gets a reference to the given Person and assigns it to the Person field.
func (o *GeneratedAttachment) SetPerson(v Person) {
	o.Person = &v
}

// GetCustomer returns the Customer field value if set, zero value otherwise.
func (o *GeneratedAttachment) GetCustomer() Customer {
	if o == nil || IsNil(o.Customer) {
		var ret Customer
		return ret
	}
	return *o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedAttachment) GetCustomerOk() (*Customer, bool) {
	if o == nil || IsNil(o.Customer) {
		return nil, false
	}
	return o.Customer, true
}

// HasCustomer returns a boolean if a field has been set.
func (o *GeneratedAttachment) HasCustomer() bool {
	if o != nil && !IsNil(o.Customer) {
		return true
	}

	return false
}

// SetCustomer gets a reference to the given Customer and assigns it to the Customer field.
func (o *GeneratedAttachment) SetCustomer(v Customer) {
	o.Customer = &v
}

// GetExternalLinks returns the ExternalLinks field value if set, zero value otherwise.
func (o *GeneratedAttachment) GetExternalLinks() []StructuredLink {
	if o == nil || IsNil(o.ExternalLinks) {
		var ret []StructuredLink
		return ret
	}
	return o.ExternalLinks
}

// GetExternalLinksOk returns a tuple with the ExternalLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedAttachment) GetExternalLinksOk() ([]StructuredLink, bool) {
	if o == nil || IsNil(o.ExternalLinks) {
		return nil, false
	}
	return o.ExternalLinks, true
}

// HasExternalLinks returns a boolean if a field has been set.
func (o *GeneratedAttachment) HasExternalLinks() bool {
	if o != nil && !IsNil(o.ExternalLinks) {
		return true
	}

	return false
}

// SetExternalLinks gets a reference to the given []StructuredLink and assigns it to the ExternalLinks field.
func (o *GeneratedAttachment) SetExternalLinks(v []StructuredLink) {
	o.ExternalLinks = v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *GeneratedAttachment) GetContent() []GeneratedAttachmentContent {
	if o == nil || IsNil(o.Content) {
		var ret []GeneratedAttachmentContent
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GeneratedAttachment) GetContentOk() ([]GeneratedAttachmentContent, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *GeneratedAttachment) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given []GeneratedAttachmentContent and assigns it to the Content field.
func (o *GeneratedAttachment) SetContent(v []GeneratedAttachmentContent) {
	o.Content = v
}

func (o GeneratedAttachment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GeneratedAttachment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StrategyName) {
		toSerialize["strategyName"] = o.StrategyName
	}
	if !IsNil(o.Documents) {
		toSerialize["documents"] = o.Documents
	}
	if !IsNil(o.Person) {
		toSerialize["person"] = o.Person
	}
	if !IsNil(o.Customer) {
		toSerialize["customer"] = o.Customer
	}
	if !IsNil(o.ExternalLinks) {
		toSerialize["externalLinks"] = o.ExternalLinks
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

type NullableGeneratedAttachment struct {
	value *GeneratedAttachment
	isSet bool
}

func (v NullableGeneratedAttachment) Get() *GeneratedAttachment {
	return v.value
}

func (v *NullableGeneratedAttachment) Set(val *GeneratedAttachment) {
	v.value = val
	v.isSet = true
}

func (v NullableGeneratedAttachment) IsSet() bool {
	return v.isSet
}

func (v *NullableGeneratedAttachment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGeneratedAttachment(val *GeneratedAttachment) *NullableGeneratedAttachment {
	return &NullableGeneratedAttachment{value: val, isSet: true}
}

func (v NullableGeneratedAttachment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGeneratedAttachment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


