/*
Glean Client API

# Introduction These are the public APIs to enable implementing a custom client interface to the Glean system.  # Usage guidelines This API is evolving fast. Glean will provide advance notice of any planned backwards incompatible changes along with a 6-month sunset period for anything that requires developers to adopt the new versions.  # SDK Client bindings for the API can be generated for most popular languages (Python, Java, NodeJS, etc). To do so:  Download the OpenAPI specification for the API, by clicking on one of the following options: 1. [Download JSON specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.json?branch=main&download=true) 2. [Download YAML specification](https://api.redocly.com/registry/bundle/glean/Glean%20Client%20API%20SDK%20source/v1/openapi.yaml?branch=main&download=true)  Use [openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli) to generate bindings for your language of choice, for example: ```bash shell $ npx @openapitools/openapi-generator-cli@latest generate -i client_api.yaml -g go ```  To see available languages: ```bash shell $ npx @openapitools/openapi-generator-cli@latest list ```  Determine the host you need to connect to. This will be the URL of the backend for your Glean deployment, for example, customer-be.glean.com 

API version: 0.9.0
Contact: support@glean.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package glean_client

import (
	"encoding/json"
)

// checks if the ShortcutsConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ShortcutsConfig{}

// ShortcutsConfig Configuration settings related to Shortcuts
type ShortcutsConfig struct {
	// Deployment's prefix for shortcuts.
	ShortcutsPrefix *string `json:"shortcutsPrefix,omitempty"`
	// Whether the deployment uses external shortcuts.
	UseExternalShortcuts *bool `json:"useExternalShortcuts,omitempty"`
}

// NewShortcutsConfig instantiates a new ShortcutsConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewShortcutsConfig() *ShortcutsConfig {
	this := ShortcutsConfig{}
	return &this
}

// NewShortcutsConfigWithDefaults instantiates a new ShortcutsConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewShortcutsConfigWithDefaults() *ShortcutsConfig {
	this := ShortcutsConfig{}
	return &this
}

// GetShortcutsPrefix returns the ShortcutsPrefix field value if set, zero value otherwise.
func (o *ShortcutsConfig) GetShortcutsPrefix() string {
	if o == nil || IsNil(o.ShortcutsPrefix) {
		var ret string
		return ret
	}
	return *o.ShortcutsPrefix
}

// GetShortcutsPrefixOk returns a tuple with the ShortcutsPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShortcutsConfig) GetShortcutsPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.ShortcutsPrefix) {
		return nil, false
	}
	return o.ShortcutsPrefix, true
}

// HasShortcutsPrefix returns a boolean if a field has been set.
func (o *ShortcutsConfig) HasShortcutsPrefix() bool {
	if o != nil && !IsNil(o.ShortcutsPrefix) {
		return true
	}

	return false
}

// SetShortcutsPrefix gets a reference to the given string and assigns it to the ShortcutsPrefix field.
func (o *ShortcutsConfig) SetShortcutsPrefix(v string) {
	o.ShortcutsPrefix = &v
}

// GetUseExternalShortcuts returns the UseExternalShortcuts field value if set, zero value otherwise.
func (o *ShortcutsConfig) GetUseExternalShortcuts() bool {
	if o == nil || IsNil(o.UseExternalShortcuts) {
		var ret bool
		return ret
	}
	return *o.UseExternalShortcuts
}

// GetUseExternalShortcutsOk returns a tuple with the UseExternalShortcuts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ShortcutsConfig) GetUseExternalShortcutsOk() (*bool, bool) {
	if o == nil || IsNil(o.UseExternalShortcuts) {
		return nil, false
	}
	return o.UseExternalShortcuts, true
}

// HasUseExternalShortcuts returns a boolean if a field has been set.
func (o *ShortcutsConfig) HasUseExternalShortcuts() bool {
	if o != nil && !IsNil(o.UseExternalShortcuts) {
		return true
	}

	return false
}

// SetUseExternalShortcuts gets a reference to the given bool and assigns it to the UseExternalShortcuts field.
func (o *ShortcutsConfig) SetUseExternalShortcuts(v bool) {
	o.UseExternalShortcuts = &v
}

func (o ShortcutsConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ShortcutsConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ShortcutsPrefix) {
		toSerialize["shortcutsPrefix"] = o.ShortcutsPrefix
	}
	if !IsNil(o.UseExternalShortcuts) {
		toSerialize["useExternalShortcuts"] = o.UseExternalShortcuts
	}
	return toSerialize, nil
}

type NullableShortcutsConfig struct {
	value *ShortcutsConfig
	isSet bool
}

func (v NullableShortcutsConfig) Get() *ShortcutsConfig {
	return v.value
}

func (v *NullableShortcutsConfig) Set(val *ShortcutsConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableShortcutsConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableShortcutsConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableShortcutsConfig(val *ShortcutsConfig) *NullableShortcutsConfig {
	return &NullableShortcutsConfig{value: val, isSet: true}
}

func (v NullableShortcutsConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableShortcutsConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


