name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.21.0'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Update Homebrew tap
        if: success()
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{ secrets.GH_PAT }}
          tap: scalvert/homebrew-tap
          formula: glean-cli
          tag: ${{ github.ref_name }}
